// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3550.RbtxStrongTaupe2016.subsystems;

import org.usfirst.frc3550.RbtxStrongTaupe2016.RobotMap;
import org.usfirst.frc3550.RbtxStrongTaupe2016.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class RbtxRamasseurSubsystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController m_moteur = RobotMap.moteurRamasseur;
    private final DigitalInput m_ballDetector = RobotMap.BallonPresent;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private static final double DIRECTION_ASPIRER = 1;
    private static final double DIRECTION_EJECTER = -1;
    private static final double VITESSE_ASPIRER = 1;
    private static final double VITESSE_ASPIRER_NORMALE = 0.75;
    private static final double VITESSE_EJECTER = 1;
    private static final double VITESSE_ZERO = 0;
    private static final boolean UPPERBALL_ISACTIVE = true; // !! verif type
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void aspirer() {
    	// AJOUTER QUAND LIMITSWITCH INSTALLE
    	//if (m_limitSwitch.get() == UPPERBALL_ISACTIVE){
    		//stop();
    	//}
    	//else{
    	    m_moteur.set(DIRECTION_ASPIRER*VITESSE_ASPIRER);
    	//}
    }
    
    public void aspirerNormalement() {
    	// AJOUTER QUAND LIMITSWITCH INSTALLE
    	//if (m_limitSwitch.get() == UPPERBALL_ISACTIVE){
    		//stop();
    	//}
    	//else{
    	    m_moteur.set(DIRECTION_ASPIRER*VITESSE_ASPIRER_NORMALE);
    	//}
    }
    
    
    public void ejecter() {
    	m_moteur.set(DIRECTION_EJECTER*VITESSE_EJECTER);
    }
    
    public void stop() {
    	m_moteur.set(VITESSE_ZERO);
    }
    
    public boolean hasBall(){
    	return m_ballDetector.get();
    }
    
}

