// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3550.RbtxStrongTaupe2016.subsystems;

import org.usfirst.frc3550.RbtxStrongTaupe2016.RobotMap;
import org.usfirst.frc3550.RbtxStrongTaupe2016.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 * The RbtxRamasseurSubsystem incorporates the sensors and actuators attached to
 * the robots grabber. These include one motor and one limit Switch to detect the ball
 * Actually the grabber is also part of the shooter
 */
public class RbtxRamasseurSubsystem extends Subsystem {

    //Declaration des composantes du sous-systeme
    private final SpeedController m_moteur    = RobotMap.moteurRamasseur;
    private final DigitalInput m_ballDetector = RobotMap.BallonPresent;

    

    private static final double DIRECTION_ASPIRER = 1;
    private static final double DIRECTION_EJECTER = -1;
    private static final double VITESSE_ASPIRER = 1;
    private static final double VITESSE_ASPIRER_NORMALE = 0.75;
    private static final double VITESSE_EJECTER = 1;
    private static final double VITESSE_ZERO = 0;
    private static final boolean UPPERBALL_ISACTIVE = true; // !! verif type
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    /**
	 * @return Whether or not the collector has the ball.
	 */
    public boolean hasBall(){
    	return m_ballDetector.get();
    }
    
    /**
	 * La methode stop est sollicitee pour completement arreter le moteur du ramasseur
	 * 
	 * @param elle ne recoit aucun argument
	 */
    public void stop() {
    	m_moteur.set(VITESSE_ZERO);
    }  
    
    /**
	 * La methode aspirerLeBallon sert de gachette pour lancer la balle. 
	 * Le rouleau du ramasseur tourne alors vers linterieur du robot
	 * La balle est alors entrainee vers l accelarateur deja en mouvement.
	 * 
	 * @param Aucun argument 
	 */
    public void aspirerLeBallon() {
    	// AJOUTER QUAND LIMITSWITCH INSTALLE
    	//if (m_limitSwitch.get() == UPPERBALL_ISACTIVE){
    		//stop();
    	//}
    	//else{
    	    m_moteur.set(DIRECTION_ASPIRER*VITESSE_ASPIRER);
    	//}
    }
    
    /**
	 * La methode aspirerNormalementLeBallon est sollicitee pour attraper la balle sur le terrain. 
	 * Le rouleau du ramasseur tourne alors vers linterieur du robot.
	 * La balle est aspiree et piegee dans le ramasseur. 
	 * La vitesse du moteur est predefinie et peut etre ajustee
	 * 
	 * @param Aucun argument
	 */
    public void aspirerNormalementLeBallon() {
    	// AJOUTER QUAND LIMITSWITCH INSTALLE
    	//if (m_limitSwitch.get() == UPPERBALL_ISACTIVE){
    		//stop();
    	//}
    	//else{
    	    m_moteur.set(DIRECTION_ASPIRER*VITESSE_ASPIRER_NORMALE);
    	//}
    }
    
    /**
	 * La methode ejecterLeBallon est sollicitee pour expulser la balle du robot. 
	 * Le rouleau du ramasseur tourne alors vers lexterieur du robot
	 * La vitesse du moteur est predefinie et peut etre ajustee
	 * @
	 * @param Aucun argument
	 */
    public void ejecterLeBallon() {
    	m_moteur.set(DIRECTION_EJECTER*VITESSE_EJECTER);
    }
    
}

